# Generated by Django 4.2.7 on 2023-11-30 17:38

import api.models
from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteConta',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(max_length=255, upload_to='')),
                ('dataNascimento', models.DateField()),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=11)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='clienteconta_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='clienteconta_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id_cliente'],
            },
            managers=[
                ('objects', api.models.ClienteManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('id_cartao', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.IntegerField()),
                ('tipo', models.CharField(choices=[('CD/CC', 'Cartão de Débito e Crédito'), ('CD', 'Cartão de Débito')], max_length=10, verbose_name='tipo')),
                ('bandeira', models.CharField(max_length=15)),
                ('situacao', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Cartao',
                'verbose_name_plural': 'Cartoes',
                'ordering': ['id_cartao'],
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('id_conta', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.IntegerField(verbose_name='Agencia')),
                ('conta', models.CharField(max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa?')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conta_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['id_conta'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('id_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dataMovimentacao', models.DateField(auto_now=True)),
                ('tipo', models.CharField(max_length=15)),
                ('id_cartao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_cartao', to='api.cartao')),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_conta', to='api.conta')),
                ('id_conta_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_destino', to='api.conta')),
            ],
            options={
                'verbose_name': 'Movimentacao',
                'verbose_name_plural': 'Movimentacoes',
                'ordering': ['id_movimentacao'],
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('id_emprestimo', models.AutoField(primary_key=True, serialize=False)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_parcelas', models.IntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprovado', models.BooleanField()),
                ('data_aprovacao', models.DateField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo_conta', to='api.conta')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
                'ordering': ['id_emprestimo'],
            },
        ),
        migrations.AddField(
            model_name='cartao',
            name='conta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_cartao', to='api.conta'),
        ),
        migrations.CreateModel(
            name='AvaliacaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('permissao', models.BooleanField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('id_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_credito_conta', to='api.conta')),
            ],
            options={
                'verbose_name': 'Avaliacao Credito',
                'verbose_name_plural': 'Avaliacoes Credito',
            },
        ),
    ]
