# Generated by Django 4.2.7 on 2023-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='limite',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='limite'),
        ),
    ]
