# Generated by Django 4.2.7 on 2023-11-30 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cartao_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaocredito',
            name='id_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conta'),
        ),
    ]
