# Generated by Django 4.2.7 on 2023-11-22 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movimentacao_id_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='id_conta_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_destino', to='api.conta'),
        ),
    ]
