# Generated by Django 4.2.7 on 2023-12-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_avaliacaocredito_id_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteconta',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clienteconta',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clienteconta',
            name='username',
            field=models.CharField(max_length=80),
        ),
    ]
